########################################################################
#
#      !!!!!! DO NOT EDIT THIS FILE !!!!!!
#
#  This file is created by yamInstall. Run yamInstall to update
#  the contents of this file.
#
########################################################################
#
# set generic  values for build  flags

#======================================================
# start off variables for C compiler

export CC_DEFINES 	=
export CC_INCLUDES	= -I$(YAM_ROOT)/include
export CC_COMPILE_FLAGS	= $(CC_OPTIMIZATION) $(ADDT_INCLUDES) \
		$(CC_DEFINES) $(CC_WARNINGS) $(CC_INCLUDES)

export CC_LIBS =
export CC_SHARED_LINK_FLAGS	=  -L$(YAM_ROOT)/lib/$(YAM_TARGET)
export CC_STATIC_LINK_FLAGS	=  -L$(YAM_ROOT)/lib/$(YAM_TARGET)-static

export SHARED_COMPILE_FLAG

#======================================================
# start off variables for C++ compiler

export CPLUSPLUS_DEFINES =
#export CPLUSPLUS_INCLUDES	:= $(CC_INCLUDES) -I$(YAM_ROOT)/include/STL
export CPLUSPLUS_INCLUDES	= $(CC_INCLUDES)
export CPLUSPLUS_COMPILE_FLAGS 	= $(CPLUSPLUS_OPTIMIZATION) $(ADDT_INCLUDES) \
		$(CPLUSPLUS_DEFINES) $(CPLUSPLUS_WARNINGS) $(CPLUSPLUS_INCLUDES)

export CPLUSPLUS_LIBS =
export CPLUSPLUS_SHARED_LINK_FLAGS    := -L$(YAM_ROOT)/lib/$(YAM_TARGET)
export CPLUSPLUS_STATIC_LINK_FLAGS    := -L$(YAM_ROOT)/lib/$(YAM_TARGET)-static

#======================================================

# set default values for 'ar' and 'ranlib' that can be overridden in
#     specific site config file if necessary

export AR = ar
export AR_FLAGS = r
export RANLIB = true
export LD = ld
