########################################################################
#
#      !!!!!! DO NOT EDIT THIS FILE !!!!!!
#
#  This file is created by yamInstall. Run yamInstall to update
#  the contents of this file.
#
########################################################################
#
# determine LOCAL_DIR

# strip out any leading /export or /tmp_mnt in the path
ifndef LOCAL_DIR
  export  LOCAL_DIR := $(shell pwd | sed -e 's@/tmp_mnt@@')
endif
