#!/usr/bin/env python
#
# pysvn client should only be accessed via self._client().

import os
import sys


def main():
    path = '../../../yam'
    for filename in os.listdir(path):
        if filename.endswith('.py'):
            full_path = os.path.join(path, filename)
            with open(full_path) as input_file:
                # Only one function should call pysvn.Client(). Everyone else
                # should call that helper function.
                if input_file.read().count('pysvn.Client(') > 1:
                    sys.stderr.write(
                        'pysvn client should only be accessed via '
                        'self._client(); found multiple calls to '
                        'pysvn.Client()\n')
                    return 2


if __name__ == '__main__':
    sys.exit(main())
