########################################################################
#
# !!!!!! DO NOT EDIT THIS FILE !!!!!!
#
# This file is created by pyam.
#
########################################################################
#
# overall file to include in a module's Makefile.yam

# if undefined, set YAM_ROOT
YAM_ROOT ?= $(shell cd ../..; pwd)
export YAM_ROOT

# set YAM_SITE if not set by the environment
# different sites can have different configuration files
# which specify compilers to use, compile flags, etc.

export YAM_SITE

SITEDEFSHOME ?= $(YAM_ROOT)/etc/SiteDefs
export SITEDEFSHOME

#-----------------------------------------------
# Site independent settings
#-----------------------------------------------
# get ALL_YAM_OS, ALL_YAM_TARGETS
# set YAM_NATIVE, YAM_OS
COMMON_DIR = $(YAM_ROOT)/common
include $(YAM_ROOT)/etc/SiteDefs/mkHome/auto/site.env

# set LOCAL_DIR
include $(SITEDEFSHOME)/mkHome/shared/localDir.mk

# set MODULE_NAME, MODULE_TYPE etc variables
include $(SITEDEFSHOME)/mkHome/shared/moduleVars.mk

#-----------------------------------------------
# Compilation, linking flags and variables
#-----------------------------------------------
# initialize values of build flags (eg. CC_DEFINES, CC_INCLUDES)
# to target independent values
ADDT_INCLUDES ?=
include $(SITEDEFSHOME)/mkHome/shared/bldFlags.mk

# set target specific (but site independent) values such as
# CC_DEFINES, CC_LIB etc
ifeq ($(SITEDEFSHOME)/targets/$(YAM_TARGET).mk,$(wildcard $(SITEDEFSHOME)/targets/$(YAM_TARGET).mk))
  include $(SITEDEFSHOME)/targets/$(YAM_TARGET).mk
endif

#-----------------------------------------------
# Site specific settings
#-----------------------------------------------
SITE_SUPPORTED_OS ?=
SITE_UNSUPPORTED_OS ?=
# get targets available for the specific site
#  first get any settings of SITE_SUPPORTED_OS, SITE_SUPPORTED_TARGETS etc.
ifdef YAM_SITE
  include $(SITEDEFSHOME)/mkHome/auto/$(YAM_SITE)-site-supported.mk
endif

# include any user specific overrides on the target build hosts
ifeq ($(HOME)/.site-hosts.mk,$(wildcard $(HOME)/.site-hosts.mk))
  include $(HOME)/.site-hosts.mk
endif

# get any specification of build directives for the module
ifeq ($(LOCAL_DIR)/.directives.mk,$(wildcard $(LOCAL_DIR)/.directives.mk))
include $(LOCAL_DIR)/.directives.mk
endif

# set the name of the site config file based on whether its for a native or cross target
ifdef YAM_TARGET
  ifeq ($(YAM_NATIVE),$(YAM_TARGET))
    CONFIGFILE=site-config-$(YAM_TARGET)
  else
    CONFIGFILE=site-config-$(YAM_NATIVE)-$(YAM_TARGET)
  endif
endif


# the user can set the SITECONFIGDIR environment variable to specify
# the path to the site config file instead of from the SiteDefs module via YAM_SITE
ifndef SITECONFIGDIR
  ifndef YAM_SITE
    $(error Error: One of either the 'YAM_SITE' or the 'SITECONFIGDIR' environment variable must be defined.!!!!!!)
  endif
endif
SITECONFIGDIR ?= $(SITEDEFSHOME)/sites/$(YAM_SITE)
SITECONFIGFILE = $(SITECONFIGDIR)/$(CONFIGFILE)
export SITECONFIGFILE


# include appropriate site-config file
ifeq ($(SITECONFIGFILE),$(wildcard $(SITECONFIGFILE)))
  include $(SITECONFIGFILE)
else
  SITECONFIGFILE=
  MODULE_UNSUPPORTED_TARGETS += $(YAM_TARGET)
endif


# set by module .supported.mk file
MODULE_SUPPORTED_OS ?=
MODULE_UNSUPPORTED_OS ?=
MODULE_SUPPORTED_TARGETS ?=
MODULE_UNSUPPORTED_TARGETS ?=
# get any specification of the module's supported targets
ifeq ($(LOCAL_DIR)/.supported.mk,$(wildcard $(LOCAL_DIR)/.supported.mk))
  include $(LOCAL_DIR)/.supported.mk
endif

# get SITE_SUPPORTED_TARGETS value
include $(SITEDEFSHOME)/mkHome/shared/supported.mk

#-----------------------------------------------
# get definitions of the generic rules
#-----------------------------------------------
include $(SITEDEFSHOME)/mkHome/auto/bldRules.mk

# rule for building YamVersion.o for Dversion. Can be included
# independently into secondary makefiles
include $(SITEDEFSHOME)/mkHome/shared/dversion.mk

# temporary stuff - delete after port to new Makeifile.yam structure
export INC_LINKS
export LIB_LINKS
export DOC_LINKS
export ETC_LINKS
export BIN_LINKS

export INC_MODULE_LINKS
export LIB_MODULE_LINKS
export DOC_MODULE_LINKS
export ETC_MODULE_LINKS
export BIN_MODULE_LINKS

# defined in modules' Makefile.yam
BIN_MODULE_LINKS ?=
DOC_MODULE_LINKS ?=
ETC_MODULE_LINKS ?=
INC_MODULE_LINKS ?=
LIB_MODULE_LINKS ?=

BIN_$(YAM_TARGET)_LINKS ?=
LIB_$(YAM_TARGET)_LINKS ?=

BIN_TARGET_LINKS ?=
LIB_TARGET_LINKS ?=
