########################################################################
#
# !!!!!! DO NOT EDIT THIS FILE !!!!!!
#
# This file is created by pyam.
#
########################################################################
#
# This file contains a list of all supported targets for the site
# The user can set either of the variables SITE_SUPPORTED_TARGETS
# or SITE_UNSUPPORTED_TARGETS.

# If neither is defined, then all targets are assumed to be supported
# and the SITE_SUPPORTED_TARGETS is set accordingly to ALL_YAM_TARGETS

# If SITE_SUPPORTED_TARGETS is not set then --
#   * The possible pool of available targets is all available unless
#     it has been restricted by the specified supported/unsupoorted OSs'.
#   * The SITE_UNSUPPORTED_TARGETS variable, if set, is used to further
#     restrict the value of SITE_SUPPORTED_TARGETS.

#==========================================================
# Site specific targets
#==========================================================
# create a default definition for SITE_UNSUPPORTED_TARGETS
# if necessary using any specified OS information
ifneq ($(SITE_SUPPORTED_TARGETS),)
  # first define the pool of unavailable targets
  SITE_UNSUPPORTED_TARGETS += $(filter-out $(SITE_SUPPORTED_TARGETS),$(ALL_YAM_TARGETS))
endif

# if only specific OS' are supported then define the list of unsupported OS'
ifneq ($(SITE_SUPPORTED_OS),)
  SITE_UNSUPPORTED_OS += $(filter-out $(ALL_YAM_OS),$(SITE_SUPPORTED_OS))
endif

# add to unsupported targets list any targets belonging to unsupported OS'
SITE_UNSUPPORTED_TARGETS += $(foreach os, $(SITE_UNSUPPORTED_OS), $($(os)_targets) )

#export SITE_UNSUPPORTED_TARGETS
ifeq ($(SITE_SUPPORTED_TARGETS),)
  SITE_SUPPORTED_TARGETS += $(filter-out $(SITE_UNSUPPORTED_TARGETS),$(ALL_YAM_TARGETS))
endif

#==========================================================
# Module specific targets
#==========================================================
# create a default definition for MODULE_SUPPORTED_TARGETS
# if necessary using any specified OS information
ifeq ($(MODULE_SUPPORTED_TARGETS),)
  # first define the pool of supported OS
  ifeq ($(MODULE_SUPPORTED_OS),)
    MODULE_SUPPORTED_OS += $(filter-out $(MODULE_UNSUPPORTED_OS),$(ALL_YAM_OS))
  endif

  MODULE_SUPPORTED_TARGETS := $(foreach os, $(MODULE_SUPPORTED_OS), $($(os)_targets))
  MODULE_SUPPORTED_TARGETS := $(filter-out $(MODULE_UNSUPPORTED_TARGETS),$(MODULE_SUPPORTED_TARGETS))
endif

# remove any site unsupported targets from the targets list
MODULE_SUPPORTED_TARGETS := $(filter-out $(SITE_UNSUPPORTED_TARGETS),$(MODULE_SUPPORTED_TARGETS))

# Do NOT export this variable because the top-level Makefile also
# includes this file and sets this variable to a generic value
# which confuses the module level makes
# If this variable relly needs to be exported then this section
# should be moved to a file of its own which the top-level Makefile
# will not need (it only cares for the value of SITE_SUPPORTED_TARGETS.
#export MODULE_SUPPORTED_TARGETS
